pipeline {
    agent any

    tools {
        maven 'Maven 3.6.1'
    }

    stages {
        stage('build') {
            steps {
                echo 'Compiling worker app'
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage('test') {
            steps {
                echo 'Running Unit Tests on worker app'
                dir('worker') {
                    sh 'mvn clean test'
                }
            }
        }

        stage('package') {
            steps {
                echo 'Packaging woker app'
                dir('worker') {
                    sh 'mvn package -D skipTests'
                }
            }
        }
    }
    post {
        failure {
            echo 'The pipeline execution has failed'
        }
        success {
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
        }
        always {
            echo 'Build pipeline is complete'
        }
    }
}
